Repository Full-Stack-Capstone/petbnb-front, pull requests merged in 2023-03, with the labels that each got.

#12 [ 1.0pt ] Setup App
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/components/App.js
  src/components/app.css
  src/index.js
  src/redux/slices/petRoomsSlice.js
  src/redux/store.js
Labels: Team Member #1, Team Member #4

#17 Home and Show Room pages
  src/components/App.js
  src/components/Extra/Filter.js
  src/components/Home/Filter.js
  src/components/Home/Home.js
  src/components/Home/home.css
  src/components/Modal/ModalRoot.js
  src/components/PetRooms/AllRooms.js
  src/components/PetRooms/Carousel.js
  src/components/PetRooms/ShowRoom.js
  src/images/petroom.jpg
  src/images/whole-room-into-a-dog-nook.jpeg
  src/redux/slices/petRoomsSlice.js
  src/redux/store.js
  src/redux/thunks/fetchRooms.js
  src/utils/CalculateRating.js
Labels: Team Member #4

#21 Add Search bard to Home Page
  src/components/Home/Home.js
  src/components/Home/RenderedRooms.js
  src/components/Home/SearchBar.js
Labels: Team Member #4

#23 Add users state and call it on home
  src/components/Extra/SearchBar.js
  src/components/Home/Home.js
  src/components/Home/RenderedRooms.js
  src/components/Pets/MyPets.js
  src/redux/slices/usersSlice.js
  src/redux/store.js
  src/redux/thunks/fetchUser.js
Labels: Team Member #4

#24 Make a Pet & List of My Pets
  src/components/PetRooms/AddRoom.js
  src/components/Pets/AddPet.js
  src/components/Pets/MyPets.js
  src/components/Pets/Pet.js
  src/components/Reservations/MakeReservation.js
  src/components/Reservations/Reservation.js
  src/redux/slices/userSlice.js
  src/redux/thunks/petThunks.js
  src/redux/thunks/userThunks.js
Labels: Team Member #1
